-- Opponent-skill analysis: per-hand grading cache and the single drill
-- template both local bots play against.

-- One summary row per graded hand. Hands are immutable once imported, so
-- caching their opponent-decision total EV loss here makes re-analysis
-- incremental: only hands without a row are re-solved.
CREATE TABLE gg_hand_analysis (
    hand_id TEXT PRIMARY KEY REFERENCES gg_hands(hand_id) ON DELETE CASCADE,
    opponent_decisions INT NOT NULL,
    ev_loss_bb_sum DOUBLE PRECISION NOT NULL,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- The field skill template generated by the analysis: one row (id = 1),
-- overwritten on every save.
CREATE TABLE drill_template (
    id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    label TEXT NOT NULL,
    skill DOUBLE PRECISION NOT NULL,
    avg_ev_loss_bb DOUBLE PRECISION NOT NULL,
    decisions INT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);